[package]
name = "qwik"
version = "0.0.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/Enigmatrix/qwik"
description = """
The `qwik` QUIC library
"""

[dependencies]
qwik-core = { path = "../qwik-core" }
qwik-crypto = { path = "../qwik-crypto" }
