[package]
name = "quik-core"
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/Enigmatrix/quik"
description = """
Core protocol implementation for the `quik` QUIC library
"""

[dependencies]
quik-util = { path = "../quik-util", version = "0.0.1" }
