[package]
name = "qwik-util"
version = "0.0.4"
edition = "2021"
license = "MIT"
repository = "https://github.com/Enigmatrix/qwik"
description = """
Utilities for the `qwik` QUIC library
"""

[dependencies]
byteorder = "1.5.0"
