[package]
name = "quik-util"
version = "0.0.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/Enigmatrix/quik"
description = """
Utilities for the `quik` QUIC library
"""

[dependencies]
byteorder = "1.5.0"
