[package]
name = "qwik-core"
version = "0.0.3"
edition = "2021"
license = "MIT"
repository = "https://github.com/Enigmatrix/qwik"
description = """
Core protocol implementation for the `qwik` QUIC library
"""

[dependencies]
qwik-util = { path = "../qwik-util" }
